[project]
name = "cryptoplatzi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "cryptography>=45.0.5",
    "numpy>=2.3.1",
]
